x = input ('plz enter the first number: ')
y = input ('plz enter the second number: ')
z = input ('plz enter the third number: ')
sum = int(x) + int(y) + int(z)
print ('add: ',sum)
multiply = int(x) * int (y) * int(z)
print('mutiplication', multiply)
division = int(x) / int (y) / int(z)
print('divide', division)
